# Generated by Django 5.0.6 on 2024-06-03 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenreToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('short', 'Short'), ('movie', 'Movie'), ('series', 'Series'), ('tvSpecial', 'TvSpecial'), ('null', 'Null')], default='null', max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('original_title', models.CharField(max_length=500)),
                ('year', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('director', models.CharField(max_length=100)),
                ('avgRating', models.FloatField()),
                ('genres', models.ManyToManyField(through='movies.GenreToken', to='movies.genre')),
            ],
        ),
        migrations.AddField(
            model_name='genretoken',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AlterUniqueTogether(
            name='genretoken',
            unique_together={('movie', 'genre')},
        ),
    ]
